name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^5.2.0

  dropdownfield: ^1.0.3
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.4.0

# modal_progress_hud: ^0.1.3

  image_picker: ^0.6.7+14

  #auto_size_text: ^2.1.0
#  flutter_vector_icons: ^0.2.1
#  google_fonts: ^1.1.1
  fluttertoast: ^7.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/

